### ISSUE TITLE
Can not connect to the celluar network

### ISSUE THREAD

**Issue by chihuo2104** [PixelOS-Devices-old/device_xiaomi_sky#1]
Something went wrong when I inserted my SIM card, it can't connect to the cellular network (5G&LTE can't work) But I can receive calls and messages.
I don't know whether this is  a bug or not so I opened this issue.
Here are some screenshots:![Screenshot_20231231-042615.png](https://github.com/PixelOS-Devices/device_xiaomi_sky/assets/38580503/9ca4f5b5-4848-41cd-961e-7f661ea3fe87)

![Screenshot_20231231-004249.png](https://github.com/PixelOS-Devices/device_xiaomi_sky/assets/38580503/0b961c47-daed-4e58-8f2c-24e6d356cfd8)

![Screenshot_20231231-004220.png](https://github.com/PixelOS-Devices/device_xiaomi_sky/assets/38580503/ddb49481-1fb9-4119-8f21-53a5c705d295)

**Comment by redducc** [comment]
Hi, you can reset apn for getting internet. Closing the issue.
